### ISSUE TITLE
pleasehave a step by step

### ISSUE THREAD

**Issue by rifaterdemsahin** [fatih-yavuz/alfred-timer-workflow#1]
installation guide 

installed bitbar.
than extracted the directory

alfred part is not clear.
a youtube video would be even better

**Comment by 5fth** [comment]
Hello,

Sorry for my late reply.
You just need to download Timer.alfredworkflow and run it. Then follow the alfred instructions stated in README.md

If you still have any problems, do not hesitate to ask.
