### ISSUE TITLE
Specify room for alert

### ISSUE THREAD

**Issue by tomclark** [fatih-yavuz/alfred-timer-workflow#2]
Hi there,

Is it possible to specify the room where the lights blink?

I have Hue lights throughout the house, and I only want them to blink in my study. I tried changing the line in the script from:

```
lights:all:reminder
```

To be:

```
groups:13:reminder
```

Where group 13 is the Hue group for my study, but nothing happens. When I use the Hue workflow to manually set the study lights to blink, the message that pops up references group 13 (and the reminder works with the Hue workflow), but it doesn't seem to work with the timer.

Any ideas?

Thanks in advance.

**Comment by fatih-yavuz** [comment]
Hi @tomclark, 

I am working on it. 

I will let you know when it is done. 

Thanks for your interest

**Comment by fatih-yavuz** [comment]
Hi @tomclark,

You can now try the new version of the workflow to specify room for the alert. 

Cheers!
